cruise_altitude = 20000.0  # ft
loiter_altitude = 10000.0  # ft
cruise_margin = 3000.0  # ft
loiter_margin = 2000.0  # ft

common_segments = 7

phase_info = {
    "pre_mission": {"include_takeoff": True, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": common_segments,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.3, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.25, 0.55), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (0.0, "ft"),
            "altitude_final": (cruise_altitude, "ft"),
            "altitude_bounds": ((0.0, cruise_altitude + cruise_margin), "ft"),
            "throttle_enforcement": "path_constraint",
            "time_initial_bounds": ((0.0, 0.0), "min"),
            "time_duration_bounds": ((30.0, 90.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([0.0, 60.0], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": common_segments,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.45, 0.55), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (cruise_altitude, "ft"),
            "altitude_final": (cruise_altitude, "ft"),
            "altitude_bounds": (
                (cruise_altitude - 3000.0, cruise_altitude + 3000.0),
                "ft",
            ),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((30.0, 90.0), "min"),
            "time_duration_bounds": ((95.0, 285.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([60.0, 190.0], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": common_segments,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.35, "unitless"),
            "mach_bounds": ((0.3, 0.55), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (cruise_altitude, "ft"),
            "altitude_final": (loiter_altitude, "ft"),
            "altitude_bounds": (
                (loiter_altitude - loiter_margin, cruise_altitude + cruise_margin),
                "ft",
            ),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((125.0, 375.0), "min"),
            "time_duration_bounds": ((25.0, 75.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([250.0, 50.0], "min")},
    },
    "cruise_LOITER": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": common_segments,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.35, "unitless"),
            "mach_final": (0.35, "unitless"),
            "mach_bounds": ((0.3, 0.4), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (loiter_altitude, "ft"),
            "altitude_final": (loiter_altitude, "ft"),
            "altitude_bounds": (
                (loiter_altitude - loiter_margin, cruise_altitude + cruise_margin),
                "ft",
            ),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((150.0, 450.0), "min"),
            "time_duration_bounds": ((90.0, 270.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([300.0, 180.0], "min")},
    },
    "climb_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": common_segments,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.35, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.3, 0.55), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (loiter_altitude, "ft"),
            "altitude_final": (cruise_altitude, "ft"),
            "altitude_bounds": (
                (loiter_altitude - loiter_margin, cruise_altitude + cruise_margin),
                "ft",
            ),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((240.0, 720.0), "min"),
            "time_duration_bounds": ((20.0, 60.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([480.0, 40.0], "min")},
    },
    "cruise_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": common_segments,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.45, 0.55), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (cruise_altitude, "ft"),
            "altitude_final": (cruise_altitude, "ft"),
            "altitude_bounds": (
                (cruise_altitude - cruise_margin, cruise_altitude + cruise_margin),
                "ft",
            ),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((260.0, 780.0), "min"),
            "time_duration_bounds": ((40.0, 120.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([520.0, 80.0], "min")},
    },
    "descent_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": common_segments,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.3, "unitless"),
            "mach_bounds": ((0.25, 0.5), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (cruise_altitude, "ft"),
            "altitude_final": (200.0, "ft"),
            "altitude_bounds": ((0.0, cruise_altitude + cruise_margin), "ft"),
            "throttle_enforcement": "path_constraint",
            "time_initial_bounds": ((300.0, 900.0), "min"),
            "time_duration_bounds": ((20.0, 60.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([600.0, 40.0], "min")},
    },
    "post_mission": {
        "include_landing": True,
        # "constrain_range": True,
        # "target_range": (3000.0, "nmi"),
    },
}
