# function which parametrically generates phase info for sardine mission
def generate_phase_info(
    altitude_optimize=False, general_mach_optimize=False, cruise_mach_optimize=False
):
    general_mach_poly_order = 3
    cruise_mach_poly_order = 3

    cruise_mach = 0.5
    num_segments = 5

    # these are distributed
    baseline_subsystem_options = {"core_aerodynamics": {"method": "computed"}}

    phase_info = {
        "pre_mission": {"include_takeoff": False, "optimize_mass": False},
        "climb_1": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": num_segments,
                "order": 3,
                "mach_optimize": general_mach_optimize,
                "mach_polynomial_order": general_mach_poly_order,
                "mach_initial": (0.3, "unitless"),
                "mach_final": (cruise_mach, "unitless"),
                "mach_bounds": ((0.25, cruise_mach + 0.1), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (0.0, "ft"),
                "altitude_final": (25_000.0, "ft"),
                "altitude_bounds": ((0.0, 30_000.0), "ft"),
                "throttle_enforcement": "path_constraint",
                "time_initial_bounds": ((0.0, 0.0), "min"),
                "time_duration_bounds": ((5.0, 75.0), "min"),
                "no_descent": True,
            },
            "initial_guesses": {"time": ([0.0, 25.0], "min")},
        },
        "cruise_1": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": num_segments,
                "order": 3,
                "mach_optimize": cruise_mach_optimize,
                "mach_polynomial_order": cruise_mach_poly_order,
                "mach_initial": (cruise_mach, "unitless"),
                "mach_final": (cruise_mach, "unitless"),
                "mach_bounds": ((cruise_mach - 0.1, cruise_mach + 0.1), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (25_000.0, "ft"),
                # "altitude_final": (25_000.0, "ft"),
                "altitude_bounds": ((10_000.0, 30_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                # "time_initial_bounds": ((10.0, 100.0), "min"),
                # "time_duration_bounds": ((120.0, 400.0), "min"),
                "target_distance": (1000.0, "nmi"),
            },
            "initial_guesses": {"time": ([15.0, 200.0], "min")},
        },
        "descent_1": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": num_segments,
                "order": 3,
                "mach_optimize": general_mach_optimize,
                "mach_polynomial_order": cruise_mach_poly_order,
                "mach_initial": (0.5, "unitless"),
                "mach_final": (0.25, "unitless"),
                "mach_bounds": ((0.2, cruise_mach), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                # "altitude_initial": (25_000.0, "ft"),
                # "altitude_final": (15_000.0, "ft"),
                "altitude_bounds": ((10_000.0, 25_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                "time_initial_bounds": ((200.0, 600.0), "min"),
                "time_duration_bounds": ((10.0, 400.0), "min"),
                "no_climb": True,
            },
            "initial_guesses": {"time": ([220.0, 20.0], "min")},
        },
        "cruise_2": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": num_segments,
                "order": 3,
                "mach_optimize": cruise_mach_optimize,
                "mach_polynomial_order": cruise_mach_poly_order,
                "mach_initial": (0.25, "unitless"),
                "mach_final": (0.25, "unitless"),
                "mach_bounds": ((0.2, 0.3), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                # "altitude_initial": (15_000.0, "ft"),
                # "altitude_final": (15_000.0, "ft"),
                "altitude_bounds": ((12_000.0, 18_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                "time_initial_bounds": ((180.0, 783.0), "min"),
                "time_duration": (180, "min"),
            },
            "initial_guesses": {"time": ([255.0, 180.0], "min")},
        },
        "climb_3": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": num_segments,
                "order": 3,
                "mach_optimize": general_mach_optimize,
                "mach_polynomial_order": general_mach_poly_order,
                "mach_initial": (0.25, "unitless"),
                "mach_final": (cruise_mach, "unitless"),
                "mach_bounds": ((0.23, cruise_mach + 0.1), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                # "altitude_initial": (15_000.0, "ft"),
                "altitude_final": (25_000.0, "ft"),
                "altitude_bounds": ((10_000.0, 30_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                "time_initial_bounds": ((330.0, 713.0), "min"),
                "time_duration_bounds": ((10.0, 30.0), "min"),
                "no_descent": True,
            },
            "initial_guesses": {"time": ([380.0, 20.0], "min")},
        },
        "cruise_3": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": num_segments,
                "order": 3,
                "mach_optimize": cruise_mach_optimize,
                "mach_polynomial_order": 3,
                "mach_initial": (0.5, "unitless"),
                "mach_final": (0.5, "unitless"),
                "mach_bounds": ((cruise_mach - 0.1, cruise_mach + 0.1), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (25_000.0, "ft"),
                # "altitude_final": (25_000.0, "ft"),
                "altitude_bounds": ((15_000.0, 30_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                # "time_initial_bounds": ((399.0, 1197.0), "min"),
                # "time_duration_bounds": ((120.0, 565.5), "min"),
                "target_distance": (1000.0, "nmi"),
            },
            "initial_guesses": {"time": ([400.0, 200.0], "min")},
        },
        "descent_2": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": num_segments,
                "order": 3,
                "mach_optimize": general_mach_optimize,
                "mach_polynomial_order": general_mach_poly_order,
                "mach_initial": (0.5, "unitless"),
                "mach_final": (0.25, "unitless"),
                "mach_bounds": ((0.2, cruise_mach + 0.1), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                # "altitude_initial": (25_000.0, "ft"),
                "altitude_final": (1500.0, "ft"),
                "altitude_bounds": ((0.0, 30_000.0), "ft"),
                "throttle_enforcement": "path_constraint",
                "time_initial_bounds": ((450.0, 700.0), "min"),
                "time_duration_bounds": ((1.0, 60.0), "min"),
                "no_climb": True,
            },
            "initial_guesses": {"time": ([600.0, 30.0], "min")},
        },
        "reserve_cruise_fixed_time": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "reserve": True,
                # Time length of this phase
                "time_duration": (45, "min"),
                "num_segments": 5,
                "order": 3,
                "distance_solve_segments": False,
                "mach_optimize": False,
                "mach_polynomial_order": 1,
                "mach_initial": (0.25, "unitless"),
                "mach_final": (0.25, "unitless"),
                "mach_bounds": ((0.15, 0.25), "unitless"),
                "altitude_optimize": False,
                "altitude_polynomial_order": 1,
                "altitude_initial": (1500.0, "ft"),
                "altitude_final": (1500.0, "ft"),
                "altitude_bounds": ((1500.0, 2000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                # "time_initial_bounds": ((550.0, 45.0), "min"),
            },
            "initial_guesses": {"time": ([630.0, 45.0], "min")},
        },
        "post_mission": {
            "include_landing": False,
            "constrain_range": False,
            # "target_range": (3000.0, "nmi"),
        },
    }
    return phase_info
