phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.3, "unitless"),
            "mach_final": (0.49, "unitless"),
            "mach_bounds": ((0.27999999999999997, 0.51), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (0.0, "ft"),
            "altitude_final": (699.0, "ft"),
            "altitude_bounds": ((0.0, 1199.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "time_initial_bounds": ((0.0, 0.0), "min"),
            "time_duration_bounds": ((11.0, 33.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([0.0, 22.0], "min")},
    },
    "climb_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.49, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.47, 0.52), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (699.0, "ft"),
            "altitude_final": (19659.0, "ft"),
            "altitude_bounds": ((199.0, 20159.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((11.0, 33.0), "min"),
            "time_duration_bounds": ((22.0, 66.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([22.0, 44.0], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.48, 0.52), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (19659.0, "ft"),
            "altitude_final": (19659.0, "ft"),
            "altitude_bounds": ((19159.0, 20159.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((33.0, 99.0), "min"),
            "time_duration_bounds": ((192.0, 576.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([66.0, 384.0], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.24, "unitless"),
            "mach_bounds": ((0.22, 0.52), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (19659.0, "ft"),
            "altitude_final": (9953.0, "ft"),
            "altitude_bounds": ((9453.0, 20159.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((225.0, 675.0), "min"),
            "time_duration_bounds": ((36.0, 108.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([450.0, 72.0], "min")},
    },
    "cruise_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.24, "unitless"),
            "mach_final": (0.25, "unitless"),
            "mach_bounds": ((0.22, 0.27), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (9953.0, "ft"),
            "altitude_final": (9953.0, "ft"),
            "altitude_bounds": ((9453.0, 10453.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((261.0, 783.0), "min"),
            "time_duration_bounds": ((110.0, 330.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([522.0, 220.0], "min")},
    },
    "climb_3": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.25, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.23, 0.52), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (9953.0, "ft"),
            "altitude_final": (19659.0, "ft"),
            "altitude_bounds": ((9453.0, 20159.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((371.0, 1113.0), "min"),
            "time_duration_bounds": ((28.0, 84.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([742.0, 56.0], "min")},
    },
    "cruise_3": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.48, 0.52), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (19659.0, "ft"),
            "altitude_final": (19659.0, "ft"),
            "altitude_bounds": ((19159.0, 20159.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((399.0, 1197.0), "min"),
            "time_duration_bounds": ((188.5, 565.5), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([798.0, 377.0], "min")},
    },
    "descent_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.24, "unitless"),
            "mach_bounds": ((0.22, 0.52), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (19659.0, "ft"),
            "altitude_final": (473.0, "ft"),
            "altitude_bounds": ((0.0, 20159.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "time_initial_bounds": ((587.5, 1762.5), "min"),
            "time_duration_bounds": ((41.0, 123.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([1175.0, 82.0], "min")},
    },
    "post_mission": {
        "include_landing": False,
        "constrain_range": True,
        "target_range": (3000.32, "nmi"),
    },
}
