from aviary.variable_info.enums import SpeedType


def define_phase_info(overrides: dict = None) -> dict:
    """Define phase info dictionaries for energy method and 2DOF method."""
    cruise_altitude = 20_000.0  # ft
    loiter_altitude = 10_000.0
    cruise_mach = 0.5  # unitless
    loiter_mach = 0.3  # unitless
    mass = 110_000.0
    range_nmi = 2000.0  # nmi

    # Energy method
    ENERGY_PHASE_INFO = {
        "pre_mission": {"include_takeoff": False, "optimize_mass": True},
        "climb1": {
            "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
            "user_options": {
                "num_segments": 5,
                "order": 3,
                "mach_optimize": False,
                "mach_bounds": ((0.08, cruise_mach), "unitless"),
                "altitude_optimize": False,
                "altitude_polynomial_order": 1,
                "altitude_bounds": ((0.0, cruise_altitude), "ft"),
                "altitude_initial": (0.0, "ft"),
                "altitude_final": (cruise_altitude, "ft"),
                "throttle_enforcement": "path_constraint",
                # "time_initial": (0.0, "min"),
                "time_duration_bounds": ((5.0, 50.0), "min"),
                "no_descent": True,
            },
            "initial_guesses": {
                "time": ([0.0, 20.0], "min"),
                # "altitude": ([0.0, cruise_altitude], "ft"),
                # "mach": ([0.2, 0.5], "unitless"),
            },
        },
        "cruise1": {
            "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
            "user_options": {
                "num_segments": 5,
                "order": 3,
                "mach_optimize": False,
                "mach_initial": (0.475, "unitless"),
                "mach_bounds": ((0.47, 0.48), "unitless"),
                "altitude_optimize": False,
                "altitude_polynomial_order": 1,
                "altitude_initial": (cruise_altitude, "ft"),
                "altitude_bounds": (
                    (cruise_altitude - 5000, cruise_altitude + 5000),
                    "ft",
                ),
                "throttle_enforcement": "boundary_constraint",
                # "time_initial_bounds": ((20.0, 200.0), "min"),
                "time_duration_bounds": ((100.0, 400.0), "min"),
            },
            "initial_guesses": {
                "time": ([20.0, 300.0], "min"),
                "altitude": ([10_000, cruise_altitude + 5000], "ft"),
                "mach": ([0.5, 0.5], "unitless"),
            },
        },
        "descent1": {
            "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
            "user_options": {
                "num_segments": 5,
                "order": 3,
                "mach_optimize": False,
                "mach_initial": (cruise_mach, "unitless"),
                "mach_final": (loiter_mach, "unitless"),
                "mach_bounds": ((0.4, 0.6), "unitless"),
                "altitude_optimize": False,
                "altitude_polynomial_order": 1,
                "altitude_initial": (cruise_altitude, "ft"),
                "altitude_final": (loiter_altitude, "ft"),
                "altitude_bounds": ((0.0, cruise_altitude), "ft"),
                "throttle_enforcement": "path_constraint",
                # "time_initial_bounds": ((100, 361.5), "min"),
                "time_duration_bounds": ((10.0, 100.0), "min"),
                "no_climb": True,
            },
            "initial_guesses": {
                "time": ([10, 30], "min"),
            },
        },
        "cruise2": {
            "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
            "user_options": {
                "num_segments": 5,
                "order": 3,
                "mach_optimize": False,
                "mach_initial": (loiter_mach, "unitless"),
                "mach_bounds": ((0.2, 0.5), "unitless"),
                "altitude_optimize": False,
                "altitude_polynomial_order": 1,
                "altitude_initial": (loiter_altitude, "ft"),
                "altitude_bounds": ((0.0, cruise_altitude), "ft"),
                "throttle_enforcement": "path_constraint",
                # "time_initial": (0.0, "min"),
                "time_duration_bounds": ((180.0, 240.0), "min"),  # 3 hour loiter
            },
            "initial_guesses": {
                "time": ([180.0, 180.0], "min"),
                "altitude": ([0.0, loiter_altitude], "ft"),
                "mach": ([0.2, 0.5], "unitless"),
            },
        },
        # "climb_2": {
        #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        #     "user_options": {
        #         "num_segments": 5,
        #         "order": 3,
        #         "mach_optimize": False,
        #         "mach_bounds": ((loiter_mach, cruise_mach), "unitless"),
        #         "mach_initial": (loiter_mach, "unitless"),
        #         "altitude_optimize": False,
        #         "altitude_initial": (loiter_altitude, "ft"),
        #         "altitude_final": (cruise_altitude, "ft"),
        #         "altitude_bounds": ((0.0, cruise_altitude), "ft"),
        #         "throttle_enforcement": "path_constraint",
        #         # "time_initial": (0.0, "min"),
        #         "time_duration_bounds": ((20.0, 200.0), "min"),
        #         "no_descent": True,
        #     },
        #     "initial_guesses": {
        #         "time": ([600, 620.0], "min"),
        #         "altitude": ([0.0, cruise_altitude], "ft"),
        #         "mach": ([0.2, 0.5], "unitless"),
        #     },
        # },
        # "cruise_2": {
        #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        #     "user_options": {
        #         "num_segments": 5,
        #         "order": 3,
        #         "mach_optimize": False,
        #         "mach_initial": (cruise_mach, "unitless"),
        #         "mach_bounds": ((0.4, 0.6), "unitless"),
        #         "altitude_optimize": False,
        #         "altitude_initial": (cruise_altitude, "ft"),
        #         "altitude_bounds": (
        #             (cruise_altitude - 5000, cruise_altitude + 5000),
        #             "ft",
        #         ),
        #         "throttle_enforcement": "boundary_constraint",
        #         # "time_initial_bounds": ((20.0, 200.0), "min"),
        #         "time_duration_bounds": ((50.0, 200.0), "min"),
        #     },
        #     "initial_guesses": {
        #         "time": ([620, 800.0], "min"),
        #         "altitude": ([10_000, cruise_altitude + 5000], "ft"),
        #         "mach": ([0.5, 0.5], "unitless"),
        #     },
        # },
        # "descent_2": {
        #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        #     "user_options": {
        #         "num_segments": 5,
        #         "order": 3,
        #         "mach_optimize": False,
        #         "mach_initial": (0.5, "unitless"),
        #         "mach_final": (0.1, "unitless"),
        #         "mach_bounds": ((0.1, 0.5), "unitless"),
        #         "altitude_optimize": False,
        #         "altitude_initial": (cruise_altitude, "ft"),
        #         "altitude_final": (500.0, "ft"),
        #         "altitude_bounds": ((0.0, loiter_altitude), "ft"),
        #         "throttle_enforcement": "path_constraint",
        #         # "time_initial_bounds": ((100, 361.5), "min"),
        #         "time_duration_bounds": ((30.0, 100.0), "min"),
        #         "no_climb": True,
        #     },
        #     "initial_guesses": {
        #         "time": ([800.0, 900.0], "min"),
        #     },
        # },
        # "post_mission": {
        #     "include_landing": False,
        #     "constrain_range": True,
        #     "target_range": (2000.0, "nmi"),
        # },
    }

    # 2DOF
    TWO_DOF_PHASE_INFO = {
        "groundroll": {
            "subsystem_options": {"core_aerodynamics": {"method": "low_speed"}},
            "user_options": {
                "num_segments": 1,
                "order": 3,
                "time_duration_ref": (50.0, "s"),
                "time_duration_bounds": ((1.0, 100.0), "s"),
                "velocity_initial": (0.066, "kn"),
                "velocity_bounds": ((0, 1000), "kn"),
                "velocity_ref": (150, "kn"),
                "mass_bounds": ((0, None), "lbm"),
                "mass_ref": (mass, "lbm"),
                "mass_defect_ref": (mass, "lbm"),
                "distance_initial": (0.0, "ft"),
                "distance_bounds": ((0, 10.0e3), "ft"),
                "distance_ref": (3000, "ft"),
                "distance_defect_ref": (3000, "ft"),
            },
            "initial_guesses": {
                "time": ([0.0, 40.0], "s"),
                "velocity": ([0.066, 143.1], "kn"),
                "distance": ([0.0, 1000.0], "ft"),
                "throttle": ([0.956, 0.956], "unitless"),
            },
        },
        "rotation": {
            "subsystem_options": {"core_aerodynamics": {"method": "low_speed"}},
            "user_options": {
                "num_segments": 2,
                "order": 3,
                "time_duration_bounds": ((1, 100), "s"),
                "time_duration_ref": (50.0, "s"),
                "velocity_bounds": ((0, 1000), "kn"),
                "velocity_ref": (100, "kn"),
                "velocity_ref0": (0, "kn"),
                "mass_bounds": ((0, None), "lbm"),
                "mass_ref": (mass, "lbm"),
                "mass_defect_ref": (mass, "lbm"),
                "distance_bounds": ((0, 10.0e3), "ft"),
                "distance_ref": (5000, "ft"),
                "distance_defect_ref": (5000, "ft"),
                "angle_of_attack_initial": (0.0, "rad"),
                "angle_of_attack_bounds": ((0.0, 5.0), "rad"),
                "angle_of_attack_ref": (5.0, "rad"),
                "angle_of_attack_defect_ref": (5.0, "rad"),
                "normal_ref": (10000, "lbf"),
            },
            "initial_guesses": {
                "time": ([40.0, 5.0], "s"),
                "angle_of_attack": ([0.0, 2.5], "deg"),
                "velocity": ([143, 150.0], "kn"),
                "distance": ([3680.37217765, 4000], "ft"),
                "throttle": ([0.956, 0.956], "unitless"),
            },
        },
        "ascent": {
            "subsystem_options": {"core_aerodynamics": {"method": "low_speed"}},
            "user_options": {
                "num_segments": 4,
                "order": 3,
                "velocity_bounds": ((0, 700), "kn"),
                "velocity_ref": (200, "kn"),
                "velocity_ref0": (0, "kn"),
                "mass_bounds": ((0, None), "lbm"),
                "mass_ref": (mass, "lbm"),
                "mass_defect_ref": (mass, "lbm"),
                "distance_bounds": ((0, 15_000), "ft"),
                "distance_ref": (1e4, "ft"),
                "distance_defect_ref": (1e4, "ft"),
                "altitude_bounds": ((0.0, 1000.0), "ft"),
                "altitude_ref": (1000, "ft"),
                "altitude_defect_ref": (1000, "ft"),
                "altitude_final": (500, "ft"),
                "altitude_constraint_ref": (500, "ft"),
                "flight_path_angle_bounds": ((-10.0, 20.0), "rad"),
                "flight_path_angle_ref": (57.2958, "deg"),
                "flight_path_angle_defect_ref": (57.2958, "deg"),
                "flight_path_angle_initial": (0.0, "deg"),
                "pitch_constraint_bounds": ((0.0, 15.0), "deg"),
                "pitch_constraint_ref": (1.0, "deg"),
            },
            "initial_guesses": {
                "time": ([45.0, 25.0], "s"),
                "flight_path_angle": ([0.0, 8.0], "deg"),
                "angle_of_attack": ([2.5, 1.5], "deg"),
                "velocity": ([150.0, 185.0], "kn"),
                "distance": ([4.0e3, 10.0e3], "ft"),
                "altitude": ([0.0, 500.0], "ft"),
                "tau_gear": (0.2, "unitless"),
                "tau_flaps": (0.9, "unitless"),
                "throttle": ([0.956, 0.956], "unitless"),
            },
        },
        # "accel": {
        #     "user_options": {
        #         "num_segments": 1,
        #         "order": 3,
        #         "alt": (500, "ft"),
        #         "EAS_constraint_eq": (250, "kn"),
        #         "time_duration_bounds": ((1, 200), "s"),
        #         "time_duration_ref": (1000, "s"),
        #         "velocity_bounds": ((150, 270), "kn"),
        #         "velocity_ref": (250, "kn"),
        #         "velocity_ref0": (150, "kn"),
        #         "mass_bounds": ((0, None), "lbm"),
        #         "mass_ref": (mass, "lbm"),
        #         "mass_defect_ref": (mass, "lbm"),
        #         "distance_bounds": ((0, 150.0), "NM"),
        #         "distance_ref": (5, "NM"),
        #         "distance_defect_ref": (5, "NM"),
        #     },
        #     "initial_guesses": {
        #         "time": ([70.0, 13.0], "s"),
        #         "velocity": ([185.0, 250.0], "kn"),
        #         "distance": ([10.0e3, 20.0e3], "ft"),
        #         "throttle": ([0.956, 0.956], "unitless"),
        #     },
        # },
        "climb1": {
            "subsystem_options": {"core_aerodynamics": {"method": "cruise"}},
            "user_options": {
                "num_segments": 4,
                "order": 3,
                "EAS_target": (250, "kn"),
                "mach_cruise": 0.475,
                "target_mach": False,
                "time_duration_bounds": ((0.5, 10), "min"),
                "time_duration_ref": (1000, "s"),
                "altitude_final": (cruise_altitude, "ft"),
                "altitude_bounds": ((300.0, cruise_altitude), "ft"),
                "altitude_ref": (cruise_altitude, "ft"),
                "mass_bounds": ((0, None), "lbm"),
                "mass_ref": (mass, "lbm"),
                "mass_defect_ref": (mass, "lbm"),
                "distance_bounds": ((0, 500.0), "NM"),
                "distance_ref": (10, "NM"),
                "distance_ref0": (0, "NM"),
            },
            "initial_guesses": {
                "time": ([1.0, 2.0], "min"),
                "distance": ([20.0e3, 100.0e3], "ft"),
                "altitude": ([400.0, cruise_altitude], "ft"),
                "throttle": ([0.956, 0.956], "unitless"),
            },
        },
        # "climb2": {
        #     "user_options": {
        #         "num_segments": 3,
        #         "order": 3,
        #         "EAS_target": (160, "kn"),
        #         "mach_cruise": 0.475,
        #         "target_mach": True,
        #         "required_available_climb_rate": (0.1, "ft/min"),
        #         "time_duration_bounds": ((200, 17_000), "s"),
        #         "time_duration_ref": (5000, "s"),
        #         "altitude_final": (21_000, "ft"),
        #         "altitude_bounds": ((9000.0, 22_000.0), "ft"),
        #         "altitude_ref": (20_000, "ft"),
        #         "altitude_ref0": (0, "ft"),
        #         "mass_bounds": ((0, None), "lbm"),
        #         "mass_ref": (150_000, "lbm"),
        #         "mass_defect_ref": (150_000, "lbm"),
        #         "distance_bounds": ((10.0, 1000.0), "NM"),
        #         "distance_ref": (500, "NM"),
        #         "distance_ref0": (0, "NM"),
        #         "distance_defect_ref": (500, "NM"),
        #     },
        #     "initial_guesses": {
        #         "time": ([216.0, 1300.0], "s"),
        #         "distance": ([100.0e3, 200.0e3], "ft"),
        #         "altitude": ([10_000, 20_000], "ft"),
        #         "throttle": ([0.956, 0.956], "unitless"),
        #     },
        # },
        "cruise1": {
            "subsystem_options": {"core_aerodynamics": {"method": "cruise"}},
            "user_options": {
                "alt_cruise": (cruise_altitude, "ft"),
                "mach_cruise": cruise_mach,
            },
            "initial_guesses": {
                # [Initial mass, delta mass] for special cruise phase.
                "mass": ([150_000.0, -35_000], "lbm"),
                "initial_distance": (100.0e3, "ft"),
                "initial_time": (1_000.0, "s"),
                "altitude": (cruise_altitude, "ft"),
                "mach": (cruise_mach, "unitless"),
            },
        },
        # "desc1": {
        #     "user_options": {
        #         "num_segments": 3,
        #         "order": 3,
        #         "EAS_limit": (160, "kn"),
        #         "mach_cruise": 0.475,
        #         "input_speed_type": SpeedType.MACH,
        #         "time_duration_bounds": ((300.0, 900.0), "s"),
        #         "time_duration_ref": (1000, "s"),
        #         "altitude_final": (cruise_altitude, "ft"),
        #         "altitude_bounds": ((1000.0, cruise_altitude + 5000), "ft"),
        #         "altitude_ref": (20_000, "ft"),
        #         "altitude_ref0": (0, "ft"),
        #         "altitude_constraint_ref": (10000, "ft"),
        #         "mass_bounds": ((0, None), "lbm"),
        #         "mass_ref": (140_000, "lbm"),
        #         "mass_ref0": (0, "lbm"),
        #         "mass_defect_ref": (140_000, "lbm"),
        #         "distance_bounds": ((1_000.0, 3_000.0), "NM"),
        #         "distance_ref": (range_nmi, "NM"),
        #         "distance_ref0": (0, "NM"),
        #         "distance_defect_ref": (100, "NM"),
        #     },
        #     "initial_guesses": {
        #         "mass": (136000.0, "lbm"),
        #         "altitude": ([cruise_altitude, loiter_altitude], "ft"),
        #         "throttle": ([0.0, 0.0], "unitless"),
        #         "distance": ([0.92 * range_nmi, 0.96 * range_nmi], "NM"),
        #         "time": ([28000.0, 500.0], "s"),
        #     },
        # },
        # "cruise_loiter": {
        #     "user_options": {
        #         # "alt_cruise": (loiter_altitude, "ft"),
        #         "mach_cruise": loiter_mach,
        #     },
        #     "initial_guesses": {
        #         # [Initial mass, delta mass] for special cruise phase.
        #         "mass": ([150_000.0, -35_000], "lbm"),
        #         "initial_distance": (100.0e3, "ft"),
        #         "initial_time": (1_000.0, "s"),
        #         "altitude": (loiter_altitude, "ft"),
        #         "mach": (loiter_mach, "unitless"),
        #     },
        # },
        # "climb_2": {
        #     "user_options": {
        #         "num_segments": 4,
        #         "order": 3,
        #         "EAS_target": (250, "kn"),
        #         "mach_cruise": 0.475,
        #         "target_mach": False,
        #         "time_duration_bounds": ((30, 300), "s"),
        #         "time_duration_ref": (1000, "s"),
        #         # "altitude_initial": (loiter_altitude, "ft"),
        #         "altitude_final": (cruise_altitude, "ft"),
        #         "altitude_bounds": ((400.0, 11_000.0), "ft"),
        #         "altitude_ref": (cruise_altitude, "ft"),
        #         "mass_bounds": ((0, None), "lbm"),
        #         "mass_ref": (150_000, "lbm"),
        #         "mass_defect_ref": (150_000, "lbm"),
        #         "distance_bounds": ((0, 500.0), "NM"),
        #         "distance_ref": (10, "NM"),
        #         "distance_ref0": (0, "NM"),
        #     },
        #     "initial_guesses": {
        #         "time": ([1.0, 2.0], "min"),
        #         "distance": ([20.0e3, 100.0e3], "ft"),
        #         "altitude": ([500.0, 10.0e3], "ft"),
        #         "throttle": ([0.956, 0.956], "unitless"),
        #     },
        # },
        # "cruise_2": {
        #     "subsystem_options": {"core_aerodynamics": {"method": "cruise"}},
        #     "user_options": {
        #         "alt_cruise": (cruise_altitude, "ft"),
        #         "mach_cruise": cruise_mach,
        #     },
        #     "initial_guesses": {
        #         # [Initial mass, delta mass] for special cruise phase.
        #         "mass": ([150_000.0, -35_000], "lbm"),
        #         "initial_distance": (100.0e3, "ft"),
        #         "initial_time": (1_000.0, "s"),
        #         "altitude": (cruise_altitude, "ft"),
        #         "mach": (cruise_mach, "unitless"),
        #     },
        # },
        "desc1": {
            "subsystem_options": {"core_aerodynamics": {"method": "cruise"}},
            "user_options": {
                "num_segments": 3,
                "order": 3,
                "EAS_limit": (160, "kn"),
                "mach_cruise": 0.475,
                "input_speed_type": SpeedType.MACH,
                "time_duration_bounds": ((5.0, 34.0), "min"),
                "time_duration_ref": (1000, "s"),
                "altitude_final": (500.0, "ft"),
                "altitude_bounds": ((500.0, cruise_altitude + 5000), "ft"),
                "altitude_ref": (cruise_altitude, "ft"),
                "altitude_ref0": (0, "ft"),
                "altitude_constraint_ref": (cruise_altitude, "ft"),
                "mass_bounds": ((0, None), "lbm"),
                "mass_ref": (140_000, "lbm"),
                "mass_ref0": (0, "lbm"),
                "mass_defect_ref": (140_000, "lbm"),
                "distance_bounds": ((1_000.0, 3_000.0), "NM"),
                "distance_ref": (range_nmi, "NM"),
                "distance_ref0": (0, "NM"),
                "distance_defect_ref": (100, "NM"),
            },
            "initial_guesses": {
                "mass": (110_000.0, "lbm"),
                # "mass": (136000.0, "lbm"),
                "altitude": ([cruise_altitude, 500], "ft"),
                "throttle": ([0.0, 0.0], "unitless"),
                "distance": ([0.92 * range_nmi, 0.96 * range_nmi], "NM"),
                "time": ([20000.0, 500.0], "s"),
            },
        },
        # "desc2": {
        #     "user_options": {
        #         "num_segments": 1,
        #         "order": 3,
        #         "EAS_limit": (250, "kn"),
        #         "mach_cruise": 0.80,
        #         "input_speed_type": SpeedType.EAS,
        #         "time_duration_bounds": ((100.0, 5000), "s"),
        #         "time_duration_ref": (500, "s"),
        #         "altitude_final": (1000, "ft"),
        #         "altitude_bounds": ((500.0, 11_000.0), "ft"),
        #         "altitude_ref": (10.0e3, "ft"),
        #         "altitude_ref0": (1000, "ft"),
        #         "altitude_constraint_ref": (1000, "ft"),
        #         "mass_bounds": ((0, None), "lbm"),
        #         "mass_ref": (150_000, "lbm"),
        #         "mass_defect_ref": (150_000, "lbm"),
        #         "distance_bounds": ((0.0, 5000.0), "NM"),
        #         "distance_ref": (3500, "NM"),
        #         "distance_defect_ref": (100, "NM"),
        #     },
        #     "initial_guesses": {
        #         "mass": (136000.0, "lbm"),
        #         "altitude": ([10.0e3, 1.0e3], "ft"),
        #         "throttle": ([0.0, 0.0], "unitless"),
        #         "distance": ([0.96 * range_nmi, range_nmi], "NM"),
        #         "time": ([28500.0, 500.0], "s"),
        #     },
        # },
    }

    return {
        "energy_phase_info": ENERGY_PHASE_INFO,
        "two_dof_phase_info": TWO_DOF_PHASE_INFO,
    }
