# sometimes these seem to be ignored?
# if both are true we run into a lack of DOF problem...
mach_optimize = False
altitude_optimize = True

phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": mach_optimize,
            "mach_polynomial_order": 1,
            "mach_initial": (0.3, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.25, 0.6), "unitless"),
            "altitude_optimize": altitude_optimize,
            "altitude_polynomial_order": 3,
            "altitude_initial": (0.0, "ft"),
            "altitude_final": (20_000.0, "ft"),
            "altitude_bounds": ((0.0, 20_000.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "time_initial_bounds": ((0.0, 0.0), "min"),
            "time_duration_bounds": ((5.0, 75.0), "min"),
            "distance_solve_segments": False,
            "no_descent": True,
        },
        "initial_guesses": {"time": ([0.0, 25.0], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": mach_optimize,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.4, 0.6), "unitless"),
            "altitude_optimize": altitude_optimize,
            "altitude_polynomial_order": 3,
            "altitude_initial": (20_000.0, "ft"),
            "altitude_final": (20_000.0, "ft"),
            "altitude_bounds": ((16_000.0, 30_000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((10.0, 100.0), "min"),
            "time_duration_bounds": ((20.0, 400.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([66.0, 384.0], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": mach_optimize,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.25, "unitless"),
            "mach_bounds": ((0.2, 0.5), "unitless"),
            "altitude_optimize": altitude_optimize,
            "altitude_polynomial_order": 3,
            "altitude_initial": (20_000.0, "ft"),
            "altitude_final": (10_000.0, "ft"),
            "altitude_bounds": ((10_000.0, 20_000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((200.0, 600.0), "min"),
            "time_duration_bounds": ((15.0, 400.0), "min"),
            "distance_solve_segments": False,
            "no_climb": True,
        },
        "initial_guesses": {"time": ([350.0, 72.0], "min")},
    },
    "cruise_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": mach_optimize,
            "mach_polynomial_order": 1,
            "mach_initial": (0.25, "unitless"),
            "mach_final": (0.25, "unitless"),
            "mach_bounds": ((0.2, 0.5), "unitless"),
            "altitude_optimize": altitude_optimize,
            "altitude_polynomial_order": 3,
            "altitude_initial": (10_000.0, "ft"),
            "altitude_final": (10_000.0, "ft"),
            "altitude_bounds": ((10_000.0, 20_000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((261.0, 783.0), "min"),
            "time_duration_bounds": ((160.0, 180.0), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([522.0, 170.0], "min")},
    },
    "climb_3": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": mach_optimize,
            "mach_polynomial_order": 1,
            "mach_initial": (0.25, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.23, 0.52), "unitless"),
            "altitude_optimize": altitude_optimize,
            "altitude_polynomial_order": 3,
            "altitude_initial": (10_000.0, "ft"),
            "altitude_final": (20_000.0, "ft"),
            "altitude_bounds": ((10_000.0, 25_000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((371.0, 1113.0), "min"),
            "time_duration_bounds": ((10.0, 60.0), "min"),
            "distance_solve_segments": False,
            "no_descent": True,
        },
        "initial_guesses": {"time": ([742.0, 56.0], "min")},
    },
    "cruise_3": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": mach_optimize,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.5, "unitless"),
            "mach_bounds": ((0.45, 0.55), "unitless"),
            "altitude_optimize": altitude_optimize,
            "altitude_polynomial_order": 3,
            "altitude_initial": (20_000.0, "ft"),
            "altitude_final": (20_000.0, "ft"),
            "altitude_bounds": ((15_000.0, 25_000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((399.0, 1197.0), "min"),
            "time_duration_bounds": ((120.0, 565.5), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([798.0, 377.0], "min")},
    },
    "descent_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 8,
            "order": 3,
            "mach_optimize": mach_optimize,
            "mach_polynomial_order": 1,
            "mach_initial": (0.5, "unitless"),
            "mach_final": (0.24, "unitless"),
            "mach_bounds": ((0.22, 0.52), "unitless"),
            "altitude_optimize": altitude_optimize,
            "altitude_polynomial_order": 3,
            "altitude_initial": (20_000.0, "ft"),
            "altitude_final": (500.0, "ft"),
            "altitude_bounds": ((0.0, 20_000.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "time_initial_bounds": ((500.0, 1200.0), "min"),
            "time_duration_bounds": ((10.0, 123.0), "min"),
            "distance_solve_segments": False,
            "no_climb": True,
        },
        "initial_guesses": {"time": ([1175.0, 82.0], "min")},
    },
    "post_mission": {
        "include_landing": False,
        "constrain_range": True,
        "target_range": (2500.0, "nmi"),
    },
}
