# sometimes these seem to be ignored?
# if both are true we run into a lack of DOF problem...


def generate_phase_info(
    altitude_optimize=False, general_mach_optimize=False, cruise_mach_optimize=False
):
    general_mach_poly_order = 3
    cruise_mach_poly_order = 3

    # these are distributed
    baseline_subsystem_options = {"core_aerodynamics": {"method": "computed"}}

    phase_info = {
        "pre_mission": {"include_takeoff": False, "optimize_mass": True},
        "climb_1": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": 8,
                "order": 3,
                "mach_optimize": general_mach_optimize,
                "mach_polynomial_order": general_mach_poly_order,
                "mach_initial": (0.3, "unitless"),
                "mach_final": (0.5, "unitless"),
                "mach_bounds": ((0.25, 0.6), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (0.0, "ft"),
                "altitude_final": (20_000.0, "ft"),
                "altitude_bounds": ((0.0, 20_000.0), "ft"),
                "throttle_enforcement": "path_constraint",
                "time_initial_bounds": ((0.0, 0.0), "min"),
                "time_duration_bounds": ((5.0, 75.0), "min"),
                "no_descent": True,
            },
            "initial_guesses": {"time": ([0.0, 25.0], "min")},
        },
        "cruise_1": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": 8,
                "order": 3,
                "mach_optimize": cruise_mach_optimize,
                "mach_polynomial_order": cruise_mach_poly_order,
                "mach_initial": (0.5, "unitless"),
                "mach_final": (0.5, "unitless"),
                "mach_bounds": ((0.4, 0.6), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (20_000.0, "ft"),
                "altitude_final": (20_000.0, "ft"),
                "altitude_bounds": ((16_000.0, 30_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                "time_initial_bounds": ((10.0, 100.0), "min"),
                "time_duration_bounds": ((180.0, 400.0), "min"),
            },
            "initial_guesses": {"time": ([25.0, 200.0], "min")},
        },
        "descent_1": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": 8,
                "order": 3,
                "mach_optimize": general_mach_optimize,
                "mach_polynomial_order": cruise_mach_poly_order,
                "mach_initial": (0.5, "unitless"),
                "mach_final": (0.25, "unitless"),
                "mach_bounds": ((0.2, 0.5), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (20_000.0, "ft"),
                "altitude_final": (10_000.0, "ft"),
                "altitude_bounds": ((10_000.0, 20_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                "time_initial_bounds": ((200.0, 600.0), "min"),
                "time_duration_bounds": ((15.0, 400.0), "min"),
                "no_climb": True,
            },
            "initial_guesses": {"time": ([225.0, 30.0], "min")},
        },
        "cruise_2": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": 8,
                "order": 3,
                "mach_optimize": cruise_mach_optimize,
                "mach_polynomial_order": cruise_mach_poly_order,
                "mach_initial": (0.25, "unitless"),
                "mach_final": (0.25, "unitless"),
                "mach_bounds": ((0.2, 0.5), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (10_000.0, "ft"),
                "altitude_final": (10_000.0, "ft"),
                "altitude_bounds": ((10_000.0, 20_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                "time_initial_bounds": ((261.0, 783.0), "min"),
                "time_duration_bounds": ((170.0, 180.0), "min"),
                # "time_duration": (180, "min"),
            },
            "initial_guesses": {"time": ([255.0, 180.0], "min")},
        },
        "climb_3": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": 8,
                "order": 3,
                "mach_optimize": general_mach_optimize,
                "mach_polynomial_order": general_mach_poly_order,
                "mach_initial": (0.25, "unitless"),
                "mach_final": (0.5, "unitless"),
                "mach_bounds": ((0.23, 0.52), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (10_000.0, "ft"),
                "altitude_final": (20_000.0, "ft"),
                "altitude_bounds": ((10_000.0, 25_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                "time_initial_bounds": ((371.0, 1113.0), "min"),
                "time_duration_bounds": ((10.0, 60.0), "min"),
                "no_descent": True,
            },
            "initial_guesses": {"time": ([435.0, 40.0], "min")},
        },
        "cruise_3": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": 8,
                "order": 3,
                "mach_optimize": cruise_mach_optimize,
                "mach_polynomial_order": 3,
                "mach_initial": (0.5, "unitless"),
                "mach_final": (0.5, "unitless"),
                "mach_bounds": ((0.45, 0.55), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (20_000.0, "ft"),
                "altitude_final": (20_000.0, "ft"),
                "altitude_bounds": ((15_000.0, 35_000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                "time_initial_bounds": ((399.0, 1197.0), "min"),
                "time_duration_bounds": ((180.0, 565.5), "min"),
            },
            "initial_guesses": {"time": ([475.0, 200.0], "min")},
        },
        "descent_2": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "num_segments": 8,
                "order": 3,
                "mach_optimize": general_mach_optimize,
                "mach_polynomial_order": general_mach_poly_order,
                "mach_initial": (0.5, "unitless"),
                "mach_final": (0.25, "unitless"),
                "mach_bounds": ((0.22, 0.52), "unitless"),
                "altitude_optimize": altitude_optimize,
                "altitude_polynomial_order": 3,
                "altitude_initial": (20_000.0, "ft"),
                "altitude_final": (1500.0, "ft"),
                "altitude_bounds": ((0.0, 20_000.0), "ft"),
                "throttle_enforcement": "path_constraint",
                "time_initial_bounds": ((500.0, 1200.0), "min"),
                "time_duration_bounds": ((10.0, 123.0), "min"),
                "no_climb": True,
            },
            "initial_guesses": {"time": ([675.0, 30.0], "min")},
        },
        "reserve_cruise_fixed_time": {
            "subsystem_options": baseline_subsystem_options,
            "user_options": {
                "reserve": True,
                # Time length of this phase
                "time_duration": (45, "min"),
                "num_segments": 5,
                "order": 3,
                "distance_solve_segments": False,
                "mach_optimize": False,
                "mach_polynomial_order": 1,
                "mach_initial": (0.25, "unitless"),
                "mach_final": (0.25, "unitless"),
                "mach_bounds": ((0.15, 0.25), "unitless"),
                "altitude_optimize": False,
                "altitude_polynomial_order": 1,
                "altitude_initial": (1500.0, "ft"),
                "altitude_final": (1500.0, "ft"),
                "altitude_bounds": ((1500.0, 2000.0), "ft"),
                "throttle_enforcement": "boundary_constraint",
                "time_initial_bounds": ((705.0, 45.0), "min"),
            },
            "initial_guesses": {"time": ([705.0, 45.0], "min")},
        },
        "post_mission": {
            "include_landing": False,
            "constrain_range": True,
            "target_range": (2500.0, "nmi"),
        },
    }
    return phase_info
