import numpy as np

phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 5,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (np.float64(0.3), "unitless"),
            "mach_final": (np.float64(0.5), "unitless"),
            "mach_bounds": (
                (np.float64(0.27999999999999997), np.float64(0.52)),
                "unitless",
            ),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (np.float64(0.0), "ft"),
            "altitude_final": (np.float64(10193.0), "ft"),
            "altitude_bounds": ((0.0, np.float64(10693.0)), "ft"),
            "throttle_enforcement": "path_constraint",
            "time_initial_bounds": ((0.0, 0.0), "min"),
            "time_duration_bounds": ((np.float64(9.0), np.float64(27.0)), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([np.float64(0.0), np.float64(18.0)], "min")},
    },
    "climb_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 5,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (np.float64(0.5), "unitless"),
            "mach_final": (np.float64(0.7), "unitless"),
            "mach_bounds": ((np.float64(0.48), np.float64(0.72)), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (np.float64(10193.0), "ft"),
            "altitude_final": (np.float64(30507.0), "ft"),
            "altitude_bounds": ((np.float64(9693.0), np.float64(31007.0)), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((np.float64(9.0), np.float64(27.0)), "min"),
            "time_duration_bounds": ((np.float64(41.5), np.float64(124.5)), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([np.float64(18.0), np.float64(83.0)], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 5,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (np.float64(0.7), "unitless"),
            "mach_final": (np.float64(0.5), "unitless"),
            "mach_bounds": ((np.float64(0.48), np.float64(0.72)), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (np.float64(30507.0), "ft"),
            "altitude_final": (np.float64(10193.0), "ft"),
            "altitude_bounds": ((np.float64(9693.0), np.float64(31007.0)), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((np.float64(50.5), np.float64(151.5)), "min"),
            "time_duration_bounds": ((np.float64(45.5), np.float64(136.5)), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([np.float64(101.0), np.float64(91.0)], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 5,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (np.float64(0.5), "unitless"),
            "mach_final": (np.float64(0.5), "unitless"),
            "mach_bounds": ((np.float64(0.48), np.float64(0.52)), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (np.float64(10193.0), "ft"),
            "altitude_final": (np.float64(10193.0), "ft"),
            "altitude_bounds": ((np.float64(9693.0), np.float64(10693.0)), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "time_initial_bounds": ((np.float64(96.0), np.float64(288.0)), "min"),
            "time_duration_bounds": ((np.float64(72.5), np.float64(217.5)), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([np.float64(192.0), np.float64(145.0)], "min")},
    },
    "descent_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "num_segments": 5,
            "order": 3,
            "mach_optimize": False,
            "mach_polynomial_order": 1,
            "mach_initial": (np.float64(0.5), "unitless"),
            "mach_final": (np.float64(0.5), "unitless"),
            "mach_bounds": ((np.float64(0.48), np.float64(0.52)), "unitless"),
            "altitude_optimize": False,
            "altitude_polynomial_order": 1,
            "altitude_initial": (np.float64(10193.0), "ft"),
            "altitude_final": (np.float64(789.0), "ft"),
            "altitude_bounds": ((np.float64(289.0), np.float64(10693.0)), "ft"),
            "throttle_enforcement": "path_constraint",
            "time_initial_bounds": ((np.float64(168.5), np.float64(505.5)), "min"),
            "time_duration_bounds": ((np.float64(29.5), np.float64(88.5)), "min"),
            "distance_solve_segments": False,
        },
        "initial_guesses": {"time": ([np.float64(337.0), np.float64(59.0)], "min")},
    },
    "post_mission": {
        "include_landing": False,
        "constrain_range": True,
        "target_range": (np.float64(3000.0), "nmi"),
    },
}
